ARG BASE_IMAGE=ghcr.io/lsst/ppdb-base:main
FROM ${BASE_IMAGE}

# Install optional requirements
RUN uv pip install --no-cache-dir --system cassandra-driver

WORKDIR /app

# Copy the entrypoint script
COPY docker/scripts/entrypoint-replication.sh .
RUN chmod +x /app/entrypoint-replication.sh

# Run the wrapper script for the ppdb-replication command
CMD ["/app/entrypoint-replication.sh"]
