name: Docker
on:
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to fetch tags, used by Python install process to
          # figure out version number
          fetch-depth: 0

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: base
        with:
          image: "lsst/ppdb-base"
          dockerfile: "docker/Dockerfile.base"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: cli
        with:
          image: "lsst/ppdb-cli"
          dockerfile: "docker/Dockerfile.cli"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          build-args: |
            BASE_IMAGE=ghcr.io/lsst/ppdb-base:${{ steps.base.outputs.tag }}

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: replication
        with:
          image: "lsst/ppdb-replication"
          dockerfile: "docker/Dockerfile.replication"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          build-args: |
            BASE_IMAGE=ghcr.io/lsst/ppdb-base:${{ steps.base.outputs.tag }}
